//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/kits.tpa"


//Initialize
LAF get_component_resources_dir RET resources_dir = dir END

//Get reference tables.
ACTION_IF (GAME_IS "iwdee") BEGIN
    LAF load_table_references STR_VAR
        table = "%resources_dir%/2da/spells-ee.2da"
    RET_ARRAY spells = references END
END ELSE BEGIN
    LAF load_table_references STR_VAR
        table = "%resources_dir%/2da/spells.2da"
    RET_ARRAY spells = references END
END


//Patches.
DEFINE_PATCH_FUNCTION make_table_replacements_paladin STR_VAR destination = "*" BEGIN
    LPF make_clab_replacements STR_VAR table = "spells" END
END

DEFINE_PATCH_FUNCTION make_table_replacements_cavalier STR_VAR destination = "*" BEGIN
    LPF add_new_spells_clab STR_VAR
        kit = "cavalier"
        table = "%resources_dir%/2da/cavalier_new_spells.2da"
    END

    LPF make_clab_replacements STR_VAR table = "spells" END
END

DEFINE_PATCH_FUNCTION make_table_replacements_undead_hunter STR_VAR destination = "*" BEGIN
    LPF add_new_spells_clab STR_VAR
        kit = "undead_hunter"
        table = "%resources_dir%/2da/undead_hunter_new_spells.2da"
    END

    LPF make_clab_replacements STR_VAR table = "spells" END
END
