//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/patchers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/spells.tpa"


//Get reference tables. Separately to avoid reference clashing.
LAF get_table_references STR_VAR
    tables = "effects"
RET_ARRAY effects = references END

LAF get_table_references STR_VAR
    tables = "subspells"
RET_ARRAY subspells = references END

LAF get_table_references STR_VAR
    tables = "spells"
RET_ARRAY spells = references END


//Patches.
//Demonic Wrath.
DEFINE_PATCH_FUNCTION demonic_wrath BEGIN
    LPF patch_resource_reference INT_VAR
        match_opcode = 146                  //Cast spell.
    STR_VAR
        resource = "demonic_wrath_knockback"
        match_resource = "knck#res"
        references = "subspells"
    END
END

//Demonic Aura.
DEFINE_PATCH_FUNCTION demonic_aura BEGIN
    LPF patch_resource_reference INT_VAR
        match_opcode = 248                  //Melee effect.
    STR_VAR
        resource = "fire_damage_2d6"
        eff = "eff"
        match_resource = ""
        references = "effects"
    END

    LPF patch_resource_reference INT_VAR
        match_opcode = 232                  //Cast spell on condition.
    STR_VAR
        resource = "demonic_aura_a"
        match_resource = ""
        references = "spells"
    END
END

//Abyssal Shield.
DEFINE_PATCH_FUNCTION abyssal_shield BEGIN
    LPF get_spell_res STR_VAR spell = "CLERIC_MAGIC_RESISTANCE" RET res = resource END
    PATCH_IF NOT ("%res%" STRING_EQUAL_CASE "*") BEGIN
        LPF CLONE_EFFECT INT_VAR
            check_globals = 0
            verbose = 1
            match_opcode = 321          //Remove effects by resource.
        STR_VAR
            insert = "first"
            resource = "%res%"
        END

        LPF CLONE_EFFECT INT_VAR
            check_globals = 0
            verbose = 1
            match_opcode = 27           //Acid resistance bonus.
            opcode = 206                //Protection from spell.
            parameter1 = 0              //Clean parameters.
            parameter2 = 0
        STR_VAR
            insert = "last"
            resource = "%res%"
        END
    END ELSE BEGIN
        PATCH_FAIL "abyssal_shield: resource for 'CLERIC_MAGIC_RESISTANCE' not found."
    END
END
