//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/encoders.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/patchers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/sectypes.tpa"


//Initialize.
LAF get_component_resources_dir RET resources = dir END

//Reference tables.
LAF load_table_references STR_VAR
    table = "%resources%/2da/items.2da"
RET_ARRAY items = references END

LAF load_table_references STR_VAR
    table = "%resources%/2da/spells.2da"
RET_ARRAY spells = references END


//Patches.
DEFINE_PATCH_FUNCTION sorcerer_inner_focus STR_VAR destination = "*" BEGIN
    LPF add_display_string INT_VAR tra_ref = 10000 END
END

DEFINE_PATCH_FUNCTION sorcerer_casting_speed STR_VAR destination = "*" BEGIN
    LPF add_display_string INT_VAR tra_ref = 10001 END
END

DEFINE_PATCH_FUNCTION sorcerer_channel_magic_d STR_VAR destination = "*" BEGIN
    //Safe as parent resource already exists.
    LPF patch_resource_reference INT_VAR
        match_opcode = 321              //Remove effects by resource.
    STR_VAR
        resource = "sorcerer_channel_magic"
        match_resource = "part#res"
        references = "spells"
    END
END

DEFINE_PATCH_FUNCTION sorcerer_channel_magic STR_VAR destination = "*" BEGIN
    LPF patch_resource_reference INT_VAR
        match_opcode = 259              //Spell trap.
    STR_VAR
        resource = "sorcerer_channel_magic_d"
        match_resource = "spl#res"
        references = "spells"
    END

    //Correct maze and imprisonment immunities.
    PATCH_WITH_SCOPE BEGIN
        PATCH_FOR_EACH animation IN
            "spmaze2"
            "spmaze1"
        BEGIN
            LPF CLONE_EFFECT INT_VAR
                check_globals = 0
                check_headers = 1
                verbose = 1
                match_opcode = 101              //Immunity to effect.
                match_parameter2 = 213          //Maze.
                multi_match = 1
                opcode = 296                    //Protection from animation.
                parameter1 = 0                  //Cleaning.
                parameter2 = 0
            STR_VAR
                resource = "%animation%"
                insert = "below"
            END
        END

        LPF CLONE_EFFECT INT_VAR
            check_globals = 0
            check_headers = 1
            verbose = 1
            match_opcode = 101              //Immunity to effect.
            match_parameter2 = 213          //Maze.
            multi_match = 1
            opcode = 169                    //Prevent icon.
            parameter1 = 0                  //Cleaning.
            parameter2 = 78                 //Maze.
        STR_VAR
            insert = "below"
        END
    END

    PATCH_WITH_SCOPE BEGIN
        LPF CLONE_EFFECT INT_VAR
            check_globals = 0
            check_headers = 1
            verbose = 1
            match_opcode = 101              //Immunity to effect.
            match_parameter2 = 211          //Imprisonment.
            multi_match = 1
            opcode = 169                    //Prevent icon.
            parameter1 = 0                  //Cleaning.
            parameter2 = 79                 //Imprisonment.
        STR_VAR
            insert = "below"
        END

        LPF encode_spell_res STR_VAR value = "WIZARD_IMPRISONMENT" RET res = return END
        LPF CLONE_EFFECT INT_VAR
            check_globals = 0
            check_headers = 1
            verbose = 1
            match_opcode = 101              //Immunity to effect.
            match_parameter2 = 211          //Imprisonment.
            multi_match = 1
            opcode = 206                    //Protection from spell.
            parameter1 = 0                  //Cleaning.
            parameter2 = 0
        STR_VAR
            resource = "%res%"
            insert = "below"
        END

        LPF encode_spell_sectype STR_VAR value = "imprisonment" RET sectype_id = return END
        LPF CLONE_EFFECT INT_VAR
            check_globals = 0
            check_headers = 1
            verbose = 1
            match_opcode = 101              //Immunity to effect.
            match_parameter2 = 211          //Imprisonment.
            multi_match = 1
            opcode = 205                    //Protection from sectype.
            parameter1 = 0                  //Cleaning.
            parameter2 = sectype_id
        STR_VAR
            insert = "below"
        END
    END
END

DEFINE_PATCH_FUNCTION sorcerer_shatter_magic STR_VAR destination = "*" BEGIN
    //Remove dispelling screen.
    LPF encode_spell_sectype STR_VAR value = "k1#dispel" RET sectype = return END
    LPF ADD_SPELL_EFFECT INT_VAR
        opcode = 221                        //Remove spell protections.
        target = 2
        parameter1 = 9
        parameter2 = sectype
        timing = 1
        resist_dispel = 2
        insert_point = 0
    END
END

DEFINE_PATCH_FUNCTION sorcerer_magic_orbs STR_VAR destination = "*" BEGIN
    LPF patch_resource_reference INT_VAR
        match_opcode = 111              //Create weapon.
    STR_VAR
        resource = "magic_orb"
        ext = "itm"
        match_resource = "item#res"
        references = "items"
    END
END
