//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/kits.tpa"


DEFINE_ACTION_FUNCTION patch_descriptions BEGIN
    LAF set_class_description INT_VAR descr = 1000 STR_VAR class = "paladin" END

    ACTION_DEFINE_ASSOCIATIVE_ARRAY descriptions BEGIN
        "cavalier" => 1010
        "inquisitor" => 1020
        "undead_hunter" => 1030
    END

    ACTION_PHP_EACH descriptions AS kit => descr BEGIN
        LAF set_kit_description INT_VAR descr = descr STR_VAR kit = "%kit%" END
    END
END

//Main loop.
LAF patch_descriptions END
