//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/kits.tpa"


//Patches.
DEFINE_ACTION_FUNCTION patch_kit_proficiencies BEGIN
    LAF get_component_resources_dir RET resources = dir END

    COPY_EXISTING "weapprof.2da" "override"
        PATCH_FOR_EACH kit IN "paladin" "cavalier" "inquisitor" "undead_hunter" BEGIN
            LPF load_array STR_VAR
                table = "%resources%/2da/%kit%_proficiencies.2da"
            RET_ARRAY proficiencies = array END

            LPF patch_proficiencies STR_VAR
                kit = "%kit%"
                array = "proficiencies"
            END
        END
    PRETTY_PRINT_2DA
    BUT_ONLY
END

//Main loop.
LAF patch_kit_proficiencies END
