//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/spells.tpa"


//Initialization.
LAF get_component_root RET root = dir END
LAF get_component_resources_dir RET resources_dir = dir END
LAF get_component_tra_dir RET tra = dir END


//Install spells.
ACTION_IF (GAME_IS "iwdee") BEGIN
    PRINT "copying spells: using spells-ee.2da table."
    LAF install_spells STR_VAR
        table = "%resources_dir%/2da/spells-ee.2da"
        dir = "%resources_dir%/spl"
        tra = "%tra%/spells.tra"
        patches = "%root%/patches/spells.tpa"
    END
END ELSE BEGIN
    LAF install_spells STR_VAR
        table = "%resources_dir%/2da/spells.2da"
        dir = "%resources_dir%/spl"
        tra = "%tra%/spells.tra"
        patches = "%root%/patches/spells.tpa"
    END
END
