//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/naming.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/symbols.tpa"


//Initialization.
LAF get_component_resources_dir RET resources = dir END


//Install spell symbols.
LAF install_extended_symbols STR_VAR
    table = "%resources%/2da/extended_symbols-ee.2da"
END

LAF install_symbols STR_VAR
    table = "%resources%/2da/symbols-ee.2da"
END
