//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"


//Initialize.
LAF get_component_root RET root = dir END
LAF get_component_resources_dir RET resources = dir END
LAF get_component_tra_dir RET tra = dir END


//Install subspells.
LAF install_resources STR_VAR
    type = "subspell"
    table = "%resources%/2da/subspells.2da"
END

//Install spells.
LAF install_resources STR_VAR
    type = "spell"
    table = "%resources%/2da/spells.2da"
    tra = "%tra%/spells.tra"
    patches = "%root%/patches/spells.tpa"
END
