//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/spells.tpa"


//Patches.
DEFINE_ACTION_FUNCTION patch_summon_deva BEGIN
    LAF get_spell_res STR_VAR spell = "PALADIN_SUMMON_DEVA" RET res_name = resource END
    ACTION_IF NOT ("%res_name%" STRING_EQUAL_CASE "*") BEGIN
        COPY_EXISTING "%res_name%.spl" "override"
            tlk_ref = RESOLVE_STR_REF ((AT 1000))
            LPF set_spell_field STR_VAR field = "description" value = "%tlk_ref%" END

            //Delete spurious headers.
            FOR (i = 10; i <= 20; ++i) BEGIN
                LPF DELETE_SPELL_HEADER INT_VAR min_level = i header_type = 1 END
            END

            //Alter duration.
            LPF ALTER_SPELL_EFFECT INT_VAR
                check_globals = 0
                verbose = 1
                match_opcode = 177          //Use Eff.
                duration = 300
            END
        BUT_ONLY
    END ELSE BEGIN
        FAIL "standardize_summon_deva: id of spell '%spell%' not found."
    END

    //Fallen deva.
    OUTER_TEXT_SPRINT res_name "spcl935"
    COPY_EXISTING "%res_name%.spl" "override"
        tlk_ref = RESOLVE_STR_REF ((AT 1010))
        LPF set_spell_field STR_VAR field = "description" value = "%tlk_ref%" END

        //Delete spurious headers.
        FOR (i = 10; i <= 20; ++i) BEGIN
            LPF DELETE_SPELL_HEADER INT_VAR min_level = i header_type = 1 END
        END

        //Alter duration.
        LPF ALTER_SPELL_EFFECT INT_VAR
            check_globals = 0
            verbose = 1
            match_opcode = 177          //Use Eff.
            duration = 300
        END
    BUT_ONLY
END


//Main loop.
LAF patch_summon_deva END
