//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/spell_symbols.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/effects.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/spells.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/tables.tpa"


//Initialization.
LAF get_component_root RET root = dir END
LAF get_component_resources_dir RET resources = dir END
LAF get_component_tra_dir RET tra = dir END


//Install spell symbols.
LAF add_spell_symbols STR_VAR
    table = "%resources%/2da/symbols.2da"
END

//Install effects.
LAF create_effects STR_VAR
    table = "%resources%/2da/effects.2da"
END

//Install spells.
LAF install_spells STR_VAR
    table = "%resources%/2da/spells.2da"
    dir = "%resources%/spl"
    tra = "%tra%/spells.tra"
    patches = "%root%/patches/spells.tpa"
END

//Install tables.
LAF install_tables STR_VAR
    table = "%resources%/2da/tables.2da"
    dir = "%resources%/2da"
    patches = "%root%/patches/tables.tpa"
END

//Patch proficiencies.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/proficiencies.tpa"
END

//Patch descriptions.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/descriptions.tpa"
    tra = "%tra%/blackguard.tra"
END

//Patch cres for Poison Weapon replacement.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/patch_cres.tpa"
END
