//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/spells.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/patchers.tpa"


//Initialize.
LAF get_component_resources_dir RET resources = dir END

//Reference tables.
LAF load_table_references STR_VAR
    table = "%resources%/2da/effects.2da"
RET_ARRAY effects = references END

LAF load_table_references STR_VAR
    table = "%resources%/2da/select.2da"
RET_ARRAY tables = references END

LAF load_table_references STR_VAR
    table = "%resources%/2da/subspells.2da"
RET_ARRAY subspells = references END


//Patches.
DEFINE_PATCH_FUNCTION archer_bow_mastery BEGIN
    //Inform user.
    LPF add_display_string INT_VAR tra_ref = 10000 END
END

DEFINE_PATCH_FUNCTION archer_evasive BEGIN
    //Inform user.
    LPF add_display_string INT_VAR tra_ref = 10010 END
END


//Called shot: disarm.
DEFINE_PATCH_FUNCTION archer_called_shot_disarm BEGIN
    LPF get_table_reference STR_VAR
        value = "archer_called_shot_disarm_a"
        array = "effects"
        ext = "eff"
    RET res = resource END

    LPF CLONE_EFFECT INT_VAR
        match_opcode = 54                   //Base thac0.
        opcode = 249                        //Ranged effect.
        parameter1 = 0                      //Clean fields.
        parameter2 = 0
    STR_VAR
        resource = "%res%"
        insert = "below"
    END
END

//Called shot: trip.
DEFINE_PATCH_FUNCTION archer_called_shot_trip BEGIN
    LPF get_table_reference STR_VAR
        value = "archer_called_shot_trip_c"
        array = "effects"
        ext = "eff"
    RET res = resource END
    
    LPF CLONE_EFFECT INT_VAR
        match_opcode = 54                   //Base thac0.
        opcode = 249                        //Ranged effect.
        parameter1 = 0                      //Clean fields.
        parameter2 = 0
    STR_VAR
        resource = "%res%"
        insert = "below"
    END
END

DEFINE_PATCH_FUNCTION archer_called_shot BEGIN
    LPF patch_resource_reference INT_VAR
        match_opcode = 214                  //Select spell.
    STR_VAR
        resource = "archer_called_shot"
        ext = "2da"
        match_resource = ""
        references = "tables"
    END
END

DEFINE_PATCH_FUNCTION archer_fashion_arrows BEGIN
    //Loop.
    FOR (i = 1; i <= 3; ++i) BEGIN
        LPF encode_table_reference STR_VAR
            value = "#suf:%i%:ARCHER_FASHION_ARROWS"
        RET res = return END

        PATCH_IF NOT (FILE_EXISTS_IN_GAME "%res%.2da") BEGIN
            PATCH_FAIL "archer_fashion_arrows: resource table '%res%.2da' not found."
        END

        //Patch in resources.
        LPF ALTER_EFFECT INT_VAR
            header = i - 1
            match_opcode = 214              //Select spell.
        STR_VAR
            match_resource = ""
            resource = "%res%"
        END
    END
END

DEFINE_PATCH_FUNCTION archer_falcon_eye BEGIN
    LPF patch_resource_reference INT_VAR
        match_opcode = 341                  //Critical hit spell.
    STR_VAR
        resource = "archer_falcon_eye_sleep"
        match_resource = ""
        references = "subspells"
    END
END
