//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/kits.tpa"


//Get reference tables.
LAF get_table_references STR_VAR
    tables = "archer_spells"
RET_ARRAY spells = references END


//Patches.
DEFINE_PATCH_FUNCTION make_table_replacements STR_VAR destination = "*" BEGIN
    PHP_EACH spells AS source => res BEGIN
        REPLACE_EVALUATE CASE_INSENSITIVE "%source%" BEGIN END "%res%"
    END
END
