//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/kits.tpa"


//Patches.
DEFINE_PATCH_FUNCTION make_table_replacements STR_VAR destination = "*" BEGIN
    //Initialize.
    LPF get_component_resources_dir RET resources = dir END

    //Get reference tables.
    LPF load_table_references STR_VAR
        table = "%resources%/2da/archer_spells.2da"
    RET_ARRAY spells = references END

    PHP_EACH spells AS source => res BEGIN
        REPLACE_EVALUATE CASE_INSENSITIVE "%source%" BEGIN END "%res%"
    END
END
