//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/kits.tpa"


//Get reference tables.
LAF load_table_references STR_VAR
    tables = "ranger_spells"
RET_ARRAY ranger_spells = references END

LAF load_table_references STR_VAR
    tables = "archer_spells"
RET_ARRAY archer_spells = references END

LAF load_table_references STR_VAR
    tables = "stalker_spells"
RET_ARRAY stalker_spells = references END

LAF load_table_references STR_VAR
    tables = "beastmaster_spells"
RET_ARRAY beastmaster_spells = references END


//Patches.
DEFINE_PATCH_FUNCTION make_table_replacements_ranger STR_VAR destination = "*" BEGIN
    LPF add_new_spells_clab STR_VAR
        kit = "ranger"
        table = "%resources_dir%/2da/ranger_new_spells.2da"
    END

    LPF make_clab_replacements STR_VAR table = "spells" END
END

DEFINE_PATCH_FUNCTION make_table_replacements_archer STR_VAR destination = "*" BEGIN
    LPF add_new_spells_clab STR_VAR
        kit = "archer"
        table = "%resources_dir%/2da/archer_new_spells.2da"
    END

    LPF merge_arrays STR_VAR
        arrays  = "ranger_spells|archer_spells"
    RET_ARRAY spells = array END

    LPF make_clab_replacements STR_VAR table = "spells" END
END

DEFINE_PATCH_FUNCTION make_table_replacements_stalker STR_VAR destination = "*" BEGIN
    LPF add_new_spells_clab STR_VAR
        kit = "stalker"
        table = "%resources_dir%/2da/stalker_new_spells.2da"
    END

    LPF merge_arrays STR_VAR
        arrays  = "ranger_spells|stalker_spells"
    RET_ARRAY spells = array END

    LPF make_clab_replacements STR_VAR table = "spells" END
END

DEFINE_PATCH_FUNCTION make_table_replacements_beastmaster STR_VAR destination = "*" BEGIN
    LPF add_new_spells_clab STR_VAR
        kit = "beastmaster"
        table = "%resources_dir%/2da/beastmaster_new_spells.2da"
    END

    LPF merge_arrays STR_VAR
        arrays  = "ranger_spells|beastmaster_spells"
    RET_ARRAY spells = array END

    LPF make_clab_replacements STR_VAR table = "spells" END
END
