//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/encoders.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/patchers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/spells.tpa"


//Initialize
LAF get_component_resources_dir RET resources = dir END

//Get reference tables.
LAF load_table_references STR_VAR
    table = "%resources%/2da/spells.2da"
RET_ARRAY spells = references END


//Patches.
DEFINE_PATCH_FUNCTION mage_aegis STR_VAR destination = "*" BEGIN
    //Patch references.
    LPF encode_spell_res STR_VAR value = "WIZARD_DISPELLING_SCREEN" RET res = return END
    LPF ALTER_EFFECT INT_VAR
        verbose = 1
        match_opcode = 321                  //remove effects by resource.
    STR_VAR
        match_resource = "dsps#res"
        resource = "%res%"
    END

    LPF ALTER_EFFECT INT_VAR
        verbose = 1
        match_opcode = 206                  //Protection from spell.
    STR_VAR
        match_resource = "dsps#res"
        resource = "%res%"
    END

    LPF patch_resource_reference INT_VAR
        match_opcode = 146                  //Cast spell.
    STR_VAR
        resource = "mage_aegis_a"
        match_resource = "dscr#res"
        references = "spells"
    END
END
