//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/spells.tpa"


//Initialize.
LAF get_component_root RET root = dir END
LAF get_component_resources_dir RET resources = dir END
LAF get_component_tra_dir RET tra = dir END


//Install spells.
LAF install_spells STR_VAR
    table = "%resources%/2da/spells.2da"
    dir = "%resources%/spl"
    tra = "%tra%/spells.tra"
    patches = "%root%/patches/spells.tpa"
END
