//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/symbols.tpa"


//Initialization.
LAF get_component_root RET root = dir END
LAF get_component_resources_dir RET resources = dir END
LAF get_component_tra_dir RET tra = dir END


//Install spell symbols.
ACTION_IF (GAME_IS "iwdee") BEGIN
    LAF install_subcomponent STR_VAR
        subcomponent = "%root%/subcomponents/symbols-ee.tpa"
    END
END ELSE BEGIN
    LAF install_symbols STR_VAR
        table = "%resources%/2da/symbols.2da"
    END
END

//Install dependent resources.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/dependencies.tpa"
END

//Install spells.
//In its own component to force reloading of ids files.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/spells.tpa"
END

//Install ability tables.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/tables.tpa"
END

//Patch proficiencies.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/proficiencies.tpa"
END

//Patch descriptions.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/descriptions.tpa"
    tra = "%tra%/kits.tra"
END
