//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/arrays.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/kits.tpa"


//Patches.
DEFINE_PATCH_FUNCTION make_table_replacements STR_VAR destination = "*" BEGIN
    //Initialization.
    LPF get_component_resources_dir RET
        resources_dir = dir
    END

    LPF add_new_spells_clab STR_VAR
        kit = "blackguard"
        table = "%resources_dir%/2da/blackguard_new_spells.2da"
    END

    //Get reference tables.
    LPF load_table_references STR_VAR
        table = "%MOD_FOLDER%/components/paladin/resources/2da/spells.2da"
    RET_ARRAY paladin_spells = references END

    LPF load_table_references STR_VAR
        table = "%resources_dir%/2da/spells.2da"
    RET_ARRAY blackguard_spells = references END

    LPF merge_arrays STR_VAR
        arrays  = "paladin_spells,blackguard_spells"
    RET_ARRAY spells = array END

    LPF make_clab_replacements STR_VAR table = "spells" END
END
