//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/kits.tpa"


//Get reference tables.
LAF get_table_references STR_VAR
    tables = "spells"
RET_ARRAY blackguard_references = references END

LAF get_table_references STR_VAR
    tables = "spells"
    dir = "%MOD_FOLDER%/components/paladin/resources/2da"
RET_ARRAY paladin_references = references END


//Patches.
DEFINE_PATCH_FUNCTION make_table_replacements STR_VAR destination = "*" BEGIN
    LPF make_clab_replacements STR_VAR array = "blackguard_references" END
    LPF make_clab_replacements STR_VAR array = "paladin_references" END
END
