//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/spells.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/tables.tpa"


//Auxiliary patching functions.
DEFINE_PATCH_FUNCTION compose_spellbook STR_VAR table = "" BEGIN
    LPF load_table STR_VAR
        file = "%table%"
        fields = "spell:level:base"
    RET_ARRAY spells_table = table END

    //Loop.
    LPF get_table_row_count STR_VAR table = "spells_table" RET row_count = count END
    FOR (i = 0; i < row_count; ++i) BEGIN
        LPF get_row_from_table INT_VAR
            row = i
        STR_VAR
            table = "spells_table"
        RET_ARRAY spells_array = array END

        PATCH_WITH_SCOPE BEGIN
            //Inject names in local scope.
            TEXT_SPRINT spell $spells_array("spell")
            TEXT_SPRINT level $spells_array("level")
            TEXT_SPRINT base $spells_array("base")

            //Get spell reference.
            LPF get_spell_res STR_VAR
                spell = "%spell%"
            RET res = resource END
            
            //Sanitize names.
            PATCH_IF (1 = base) AND ("%res%" STRING_EQUAL_CASE "*") BEGIN
                PATCH_FAIL "compose_spellbook: spell '%spell%' not found in 'spell.ids'."
            END

            //Add spell.
            PATCH_IF NOT ("%res%" STRING_EQUAL_CASE "*") BEGIN
                LPF ADD_SPELL_EFFECT INT_VAR
                    opcode = 172            //Remove spell.
                    target = 2
                    timing = 4              //Delayed as in KR; with instant, sometimes it did not apply.
                    duration = 1
                    insert_point = 0 - 1    //Append.
                STR_VAR
                    resource = "%res%"
                END
            END
        END
    END
END

//Utilities.
DEFINE_ACTION_FUNCTION gather_ranger_spell_levels RET_ARRAY array BEGIN
    ACTION_DEFINE_ASSOCIATIVE_ARRAY array BEGIN END

    COPY - "%MOD_FOLDER%/components/%COMPONENT%/resources/2da/ranger_spell_progression.2da" "weidu_external/%MOD_FOLDER%"
        COUNT_2DA_COLS cols
        COUNT_2DA_ROWS cols row_count

        //In each column find first non-zero entrance.
        FOR (col = 1; col < cols; ++col) BEGIN
            found = 0
            FOR (row = 0; (row < row_count) AND (found = 0); ++row) BEGIN
                READ_2DA_ENTRY row 0 cols level
                READ_2DA_ENTRY row col cols first
                PATCH_IF (first != 0) BEGIN
                    TEXT_SPRINT $array("%col%") "%level%"
                    found = 1
                END
            END
        END
    
    //Add zeroth entry.
    TEXT_SPRINT $array("0") "1"
END

DEFINE_ACTION_FUNCTION gather_druid_spells RET_ARRAY array BEGIN
    //Initialize array.
    ACTION_DEFINE_ASSOCIATIVE_ARRAY array BEGIN END

    COPY_EXISTING - "spell.ids" "weidu_external/%MOD_FOLDER%/%COMPONENT%"
        COUNT_2DA_ROWS 2 rows
        //Loop.
        FOR (i = 0; i < rows; ++i) BEGIN
            READ_2DA_ENTRY i 0 2 nbr
            READ_2DA_ENTRY i 1 2 spell

            //Filter spurious signature entry.
            PATCH_IF NOT ("%spell%" STRING_EQUAL_CASE "v1.0") BEGIN
                //Filter out non-priest spellbook spells.
                PATCH_IF (1000 <= nbr) AND (nbr < 2000) BEGIN
                    //Filter out deprecated spells.
                    PATCH_IF NOT (("%spell%" STRING_MATCHES_REGEXP ".+_DEPRECATED") = 0) BEGIN
                        LPF get_spell_res STR_VAR spell = "%spell%" RET resource END

                        //Filter out non_existent spells.
                        PATCH_IF FILE_EXISTS_IN_GAME "%resource%.spl" BEGIN
                            //Gather info.
                            INNER_ACTION BEGIN
                                COPY_EXISTING - "%resource%.spl" "override"
                                    LPF get_spell_field STR_VAR field = "level" RET level = value END
                                    LPF get_spell_field STR_VAR field = "exclusion" RET exclusion = value END
                            END
                        END

                        //Filter by level and exclusion.
                        is_druid = exclusion BAND (1 << 30)
                        PATCH_IF (1 <= level) AND (level <= 7) AND (is_druid != 0) BEGIN
                            TEXT_SPRINT $array("%spell%") "%level%"
                        END
                    END
                END
            END
        END
END

//Patchers.
DEFINE_PATCH_FUNCTION clone_to_display_string INT_VAR
    check_headers = 1
    check_globals = 0
    header = 0 - 1
    match_opcode = 142
    tra_ref = 0
STR_VAR
    insert = "below"
BEGIN
    //Resolve reference.
    tlk_ref = RESOLVE_STR_REF ((AT tra_ref))

    //Insert opcode.
    LPF CLONE_EFFECT INT_VAR
        check_globals = check_globals
        check_headers = check_headers
        verbose = 1
        header = header
        match_opcode = match_opcode
        opcode = 139                        //Display string.
        parameter1 = tlk_ref
        parameter2 = 0                      //Clean.
        timing = 1                          //Instantaneous.
        duration = 0
        special = 0                         //Clean.
    STR_VAR
        resource = ""                       //Clean.
        insert = "%insert%"
    END
END
