//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/spells.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/tables.tpa"


//Auxiliary patching functions.
DEFINE_PATCH_FUNCTION compose_spellbook STR_VAR table = "" BEGIN
    LPF load_table STR_VAR
        file = "%table%"
        fields = "spell:level:base"
    RET_ARRAY spells_table = table END

    //Loop.
    LPF get_table_row_count STR_VAR table = "spells_table" RET row_count = count END
    FOR (i = 0; i < row_count; ++i) BEGIN
        LPF get_row_from_table INT_VAR
            row = i
        STR_VAR
            table = "spells_table"
        RET_ARRAY spells_array = array END

        PATCH_WITH_SCOPE BEGIN
            //Inject names in local scope.
            TEXT_SPRINT spell $spells_array("spell")
            TEXT_SPRINT level $spells_array("level")
            TEXT_SPRINT base $spells_array("base")

            //Get spell reference.
            LPF get_spell_res STR_VAR
                spell = "%spell%"
            RET res = resource END
            
            //Sanitize names.
            PATCH_IF (1 = base) AND ("%res%" STRING_EQUAL_CASE "*") BEGIN
                PATCH_FAIL "compose_spellbook: spell '%spell%' not found in 'spell.ids'."
            END

            //Add spell.
            PATCH_IF NOT ("%res%" STRING_EQUAL_CASE "*") BEGIN
                LPF ADD_SPELL_EFFECT INT_VAR
                    opcode = 172            //Remove spell.
                    target = 2
                    timing = 4              //Delayed as in KR; with instant, sometimes it did not apply.
                    duration = 1
                    insert_point = 0 - 1    //Append.
                STR_VAR
                    resource = "%res%"
                END
            END
        END
    END
END

//Utilities.
DEFINE_PATCH_FUNCTION gather_druid_spells INT_VAR min_level = 1 RET_ARRAY array BEGIN
    //Initialize array.
    PATCH_DEFINE_ARRAY array BEGIN END
    INNER_ACTION BEGIN
        COPY_EXISTING - "spell.ids" "weidu_external/%MOD_FOLDER%/%COMPONENT%"
            COUNT_2DA_ROWS 2 rows
            //Loop.
            FOR (i = 0; i < rows; ++i) BEGIN
                READ_2DA_ENTRY i 0 2 nbr
                READ_2DA_ENTRY i 1 2 spell

                //Filter spurious signature entry.
                PATCH_IF NOT ("%spell%" STRING_EQUAL_CASE "v1.0") BEGIN
                    //Filter out non-priest spellbook spells.
                    PATCH_IF (1000 <= nbr) AND (nbr < 2000) BEGIN
                        //Filter out deprecated spells.
                        PATCH_IF NOT (("%spell%" STRING_MATCHES_REGEXP ".+_DEPRECATED") = 0) BEGIN
                            LPF get_spell_res STR_VAR spell = "%spell%" RET resource END
                            //Filter out non_existent spells.
                            PATCH_IF FILE_EXISTS_IN_GAME "%resource%.spl" BEGIN
                                //Gather info.
                                INNER_ACTION BEGIN
                                    COPY_EXISTING - "%resource%.spl" "override"
                                        LPF get_spell_field STR_VAR field = "level" RET level = value END
                                        LPF get_spell_field STR_VAR field = "exclusion" RET exclusion = value END
                                END
                            END
                            //Filter by level and exclusion.
                            is_druid = exclusion BAND (1 << 30)
                            PATCH_IF (min_level <= level) AND (level <= 7) AND (is_druid != 0) BEGIN
                                TEXT_SPRINT $array("%spell%") "%level%"
                            END
                        END
                    END
                END
            END
    END
END
