//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/spell_symbols.tpa"


//Initialization.
LAF get_component_root RET root = dir END
LAF get_component_resources_dir RET resources = dir END
LAF get_component_tra_dir RET tra = dir END


//Install spell symbols.
LAF add_spell_symbols STR_VAR
    table = "%resources%/2da/symbols.2da"
END

//Install items.
ACTION_IF (GAME_IS "eet") BEGIN
    LAF install_resources STR_VAR
        type = "copy_item_simplified"
        table = "%resources%/2da/items_eet.2da"
        tra = "%tra%/items.tra"
    END
END

ACTION_IF (GAME_INCLUDES "iwd") BEGIN
    LAF install_resources STR_VAR
        type = "copy_item_simplified"
        table = "%resources%/2da/items_iwd.2da"
        tra = "%tra%/items.tra"
    END
END ELSE BEGIN
    LAF install_resources STR_VAR
        type = "copy_item_simplified"
        table = "%resources%/2da/items_bg2ee.2da"
        tra = "%tra%/items.tra"
    END
END

//Install cres.
LAF install_resources STR_VAR
    type = "creature"
    table = "%resources%/2da/creatures.2da"
    tra = "%tra%/creatures.tra"
    patches = "%root%/patches/creatures.tpa"
END

//Install subspells.
LAF install_resources STR_VAR
    type = "subspell"
    table = "%resources%/2da/subspells.2da"
END

//Install effects.
LAF install_resources STR_VAR
    type = "create_effect"
    table = "%resources%/2da/effects.2da"
END

//Install select tables for spells.
LAF install_resources STR_VAR
    type = "table"
    table = "%resources%/2da/select.2da"
    patches = "%root%/patches/select.tpa"
END

//Install spells.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/spells.tpa"
END

//Install tables.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/tables.tpa"
END

//Patch proficiencies.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/proficiencies.tpa"
END

//Patch stalker backstab table.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/backstab.tpa"
END

//Patch cleric ability table.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/patch_cleric_table.tpa"
END

//Patch descriptions.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/descriptions.tpa"
    tra = "%tra%/descriptions.tra"
END
