//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/creatures.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/ids.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/spells.tpa"
//Internal.
INCLUDE "%WEIDU_LIBRARY_DIR%/internal/binary.tpa"



//Patches.
DEFINE_PATCH_FUNCTION patch_known_spells STR_VAR old = "" new = "" BEGIN
    GET_OFFSET_ARRAY known_spells CRE_V10_KNOWN_SPELLS
    PHP_EACH known_spells AS _ => known_spell_offset BEGIN
        LPF read_resource INT_VAR offset = known_spell_offset RET spell = value END
        PATCH_IF ("%old%" STRING_EQUAL_CASE "%spell%") BEGIN
            LPF write_resource INT_VAR offset = known_spell_offset STR_VAR value = "%new%" END
        END
    END
END


//Action functions.
DEFINE_ACTION_FUNCTION patch_cre_files BEGIN
    //Initialize.
    LAF get_id_from_ids STR_VAR ids = "kit" value = "blackguard" RET blackguard_id = id END
    OUTER_SET blackguard_id = blackguard_id << 16

    LAF get_spell_res STR_VAR spell = "ASSASSIN_POISON" RET old_poison_weapon = resource END
    ACTION_IF ("%old_poison_weapon%" STRING_EQUAL_CASE "*") OR (NOT (FILE_EXISTS_IN_GAME "%old_poison_weapon%.spl")) BEGIN
        FAIL "patch_cres: resource for 'ASSASSIN_POISON' not found."
    END

    LAF get_spell_res STR_VAR spell = "BLACKGUARD_POISON_WEAPON" RET new_poison_weapon = resource END
    ACTION_IF ("%new_poison_weapon%" STRING_EQUAL_CASE "*") OR (NOT (FILE_EXISTS_IN_GAME "%new_poison_weapon%.spl")) BEGIN
        FAIL "patch_cres: resource for 'BLACKGUARD_POISON_WEAPON' not found."
    END

    //Patch cre files.
    COPY_EXISTING_REGEXP ".*\.cre" "override"
        LPF get_cre_field STR_VAR field = "kit" RET kit_value = value END
        PATCH_IF blackguard_id = kit_value BEGIN
            PATCH_PRINT "patch_cres: patching '%SOURCE_FILE%'."

            //Patches.
            LPF patch_known_spells STR_VAR old = "%old_poison_weapon%" new = "%new_poison_weapon%" END
        END
        BUT_ONLY
END


//Main loop.
LAF patch_cre_files END
