//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/arrays.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/kits.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/spells.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/tables.tpa"


//Action functions.
DEFINE_ACTION_FUNCTION patch_backstab_table STR_VAR kit = "" table = "" dir = "*" BEGIN
    ACTION_IF ("%dir%" STRING_EQUAL_CASE "*") BEGIN
        LAF get_component_resources_dir RET dir END
        OUTER_TEXT_SPRINT dir "%dir%/2da"
    END

    //Set table.
    OUTER_TEXT_SPRINT source "%dir%/%table%"

    //Build table from 2da.
    LAF load_array STR_VAR
        table = "%source%"
    RET_ARRAY backstab_table = array END

    //Patch backltab table.
    COPY_EXISTING "backstab.2da" "override"
        //Find kit row.
        LPF find_row_index STR_VAR key = "%kit%" RET row = index END
        PATCH_IF (row = 0 - 1) BEGIN
            PATCH_FAIL "patch_backstab_table: cannot find kit '%kit%' in 'backstab.2da'."
        END

        COUNT_2DA_COLS cols
        FOR (i = 0; i < cols - 1; ++i) BEGIN
            SET_2DA_ENTRY row (i + 1) cols $"backstab_table"("%i%")
        END
    PRETTY_PRINT_2DA
    BUT_ONLY
END


//Main loop.
LAF patch_backstab_table STR_VAR
    kit = "stalker"
    table = "stalker_backstab.2da"
END
