//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/2da.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/spells.tpa"


//Load tables.
LAF get_table_references STR_VAR
    tables = "ranger_spells"
RET_ARRAY spells = references END


//Patches.
DEFINE_ACTION_FUNCTION patch_cleric_clab BEGIN
    COPY_EXISTING "clabpr01.2da" "override"
        COUNT_2DA_COLS cols
        COUNT_2DA_ROWS cols row_count

        //Add three rows.
        FOR (i = row_count + 1; i < row_count + 4; ++i) BEGIN
            LPF append_row STR_VAR key = "ABILITY%row_count%" default = "****" END
        END

        //Add abilities to handle dual classes.
        LPF get_table_ref STR_VAR
            value = "ranger_dual_protection_level_bonus"
            array = "ranger_spells"
            ext = "spl"
        RET res = resource END
        SET_2DA_ENTRY (row_count + 1) 1 cols "AP_%res%"

        LPF get_table_ref STR_VAR
            value = "ranger_dual_remove_level_bonus"
            array = "ranger_spells"
            ext = "spl"
        RET res = resource END
        SET_2DA_ENTRY (row_count + 2) 1 cols "AP_%res%"

        //Add abilities to handle multi classes.
        LPF get_table_ref STR_VAR
            value = "ranger_spellbook"
            array = "ranger_spells"
            ext = "spl"
        RET res = resource END
        FOR (i = 1; i < cols; ++i) BEGIN
            SET_2DA_ENTRY (row_count + 3) i cols "AP_%res%"
        END
    PRETTY_PRINT_2DA
    BUT_ONLY
END

//Main loop.
LAF patch_cleric_clab END
