//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"


//Initialization.
LAF get_component_root RET root = dir END
LAF get_component_resources_dir RET resources = dir END
LAF get_component_tra_dir RET tra = dir END


//Install spell symbols.
LAF install_resources STR_VAR
    type = "add_symbol"
    table = "%resources%/2da/symbols.2da"
END

//Install effects.
LAF install_resources STR_VAR
    type = "create_effect"
    table = "%resources%/2da/effects.2da"
END

//Install subspells.
LAF install_resources STR_VAR
    type = "subspell"
    table = "%resources%/2da/subspells.2da"
END

//Install spells.
LAF install_resources STR_VAR
    type = "spell"
    table = "%resources%/2da/spells.2da"
    tra = "%tra%/spells.tra"
    patches = "%root%/patches/spells.tpa"
END

//Deduplicate table and install hlas.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/hla_tables.tpa"
END
