//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/hlas.tpa"


//Deduplicate tables.
DEFINE_ACTION_FUNCTION deduplicate_tables BEGIN
    LAF get_hla_table STR_VAR kit = "paladin" RET original = table END
    LAF replace_table STR_VAR kit = "blackguard" original = "%original%" new = "pa4" END
END

DEFINE_ACTION_FUNCTION patch_hla_tables BEGIN
    ACTION_FOR_EACH kit IN
        "blackguard"
    BEGIN
        LAF get_component_resources_dir RET resources = dir END
        LAF patch_hla_table STR_VAR
            kit = "%kit%"
            deletions = "%resources%/2da/%kit%_hlas_delete.2da"
            additions = "%resources%/2da/%kit%_hlas_add.2da"
        END
    END
END


//Main loop.
LAF deduplicate_tables END
LAF patch_hla_tables END
