//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/patchers.tpa"


//Get reference tables.
LAF get_table_references STR_VAR
    tables = "subspells"
RET_ARRAY subspells = references END


//Patches.
DEFINE_PATCH_FUNCTION shambling_mound_fists STR_VAR destination = "*" BEGIN
    LPF patch_resource_reference INT_VAR
        match_opcode = 146                  //Cast spell.
    STR_VAR
        resource = "shambling_mound_fists_entangle"
        match_resource = "spl#res"
        references = "subspells"
    END
END

DEFINE_PATCH_FUNCTION wyvern_bite STR_VAR destination = "*" BEGIN
    LPF patch_resource_reference INT_VAR
        match_opcode = 146                  //Cast spell.
    STR_VAR
        resource = "greater_wyvern_bite_poisoning"
        match_resource = "spl#res"
        references = "subspells"
    END
END

DEFINE_PATCH_FUNCTION black_spider_sting STR_VAR destination = "*" BEGIN
    LPF patch_resource_reference INT_VAR
        match_opcode = 146                  //Cast spell.
    STR_VAR
        resource = "black_spider_sting_web"
        match_resource = "spl#res"
        references = "subspells"
    END
END
