//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/spell_symbols.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/projectiles.tpa"


//Initialization.
LAF get_component_root RET root = dir END
LAF get_component_resources_dir RET resources_dir = dir END
LAF get_component_tra_dir RET tra = dir END


//Install spell symbols.
LAF add_spell_symbols STR_VAR
    table = "%resources_dir%/2da/symbols.2da"
END

//Install projectiles.
LAF add_projectiles STR_VAR
    table = "%resources_dir%/2da/projectiles.2da"
    dir = "%resources_dir%/pro"
END

//Install hla spells.
//In its own component to force reloading of ids files.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/spells.tpa"
END

//Deduplicate tables and install hlas.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/hla_tables.tpa"
END

LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/standardize_summon_deva.tpa"
    tra = "%tra%/deva.tra"
END
