//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/spell_symbols.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/creatures.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/effects.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/items.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers/subspells.tpa"


//Initialization.
LAF get_component_root RET root = dir END
LAF get_component_resources_dir RET resources = dir END
LAF get_component_tra_dir RET tra = dir END


//Install spell symbols.
LAF add_spell_symbols STR_VAR
    table = "%resources%/2da/symbols.2da"
END

LAF create_effects STR_VAR
    table = "%resources%/2da/effects.2da"
END

//Subspells for items.
LAF clone_subspells STR_VAR
    table = "%resources%/2da/subspells.2da"
END

//Items for summons.
LAF install_items STR_VAR
    table = "%resources%/2da/items.2da"
    dir = "%resources%/itm"
    tra = "%tra%/items.tra"
    patches = "%root%/patches/items.tpa"
END

//Summons.
LAF install_creatures STR_VAR
    table = "%resources%/2da/creatures.2da"
    dir = "%resources%/cre"
    tra = "%tra%/creatures.tra"
    patches = "%root%/patches/creatures.tpa"
END

//Install hlas.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/spells.tpa"
END

//Deduplicate tables and patch hla tables.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/hla_tables.tpa"
END
