//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"


//Initialization.
LAF get_component_root RET root = dir END
LAF get_component_resources_dir RET resources = dir END
LAF get_component_tra_dir RET tra = dir END

//Install spell symbols.
LAF install_resources STR_VAR
    type = "add_symbol"
    table = "%resources%/2da/symbols.2da"
END

LAF install_resources STR_VAR
    type = "create_effect"
    table = "%resources%/2da/effects.2da"
END

//Subspells for items.
LAF install_resources STR_VAR
    type = "subspell"
    table = "%resources%/2da/subspells.2da"
END

//Items for summons.
LAF install_resources STR_VAR
    type = "item"
    table = "%resources%/2da/items.2da"
    tra = "%tra%/items.tra"
    patches = "%root%/patches/items.tpa"
END

//Summons.
LAF install_resources STR_VAR
    type = "creature"
    table = "%resources%/2da/creatures.2da"
    tra = "%tra%/creatures.tra"
    patches = "%root%/patches/creatures.tpa"
END

//Install hlas.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/spells.tpa"
END

//Deduplicate tables and patch hla tables.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/hla_tables.tpa"
END
